### PR TITLE
add copy button to rule remediation

### PR DESCRIPTION
**Pull request by orouz**
Fixes 
- https://github.com/elastic/security-team/issues/2432

Screen Shot 2021-12-09 at 18 01 34

TODO: 
- we need to figure out what to do with remediations that aren't a copy-paste command and include some informative text as well. 
for example, rule  `1.2.9` has to following remediation:
```
Edit the API server pod specification file /etc/kubernetes/manifests/kube-apiserver.yaml on the master node and set the --authorization-mode parameter to a value that includes RBAC, for example: --authorization-mode=Node,RBAC
```

which isn't a command per-say, but maybe we can extract something from it. 

in anyway, this means the rule interface would need to include a property that indicates the type of remediation - text/command so we can tell if it needs to be copied. possibly other fields to provide a better experience. 

@amar-rama-build, @oren-zohar  - wdyt ?

### CODE REVIEW

**Comment by oren-zohar** [comment]
@orouz This makes sense, I'll update the remediation to be an object with an indicator.

**Comment by orouz** [comment]
OK 

this branch needs some fixing as it's been a while

**Review by ari-aviran — CHANGES_REQUESTED** [review]
Please either update this branch or open a new PR based on `csp_shared_root`

**Comment by orouz** [comment]
> This makes sense, I'll update the remediation to be an object with an indicator.

@oren-zohar any updates on the new interface to indicate remediation type?

**Pull request closed without merging**
